app:
  prefix: '/api'
  port: 8081
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'

# 数据库配置
db:
  mysql:
    host: '139.198.30.87'
    username: 'root'
    password: 'root'
    database: 'test'
    port: 3306
    charser: 'utf8mb4'
    logger: 'advanced-console'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: true
    supportBigNumbers: true
    bigNumberStrings: true
